import {nextui} from '@nextui-org/theme';
import tailwindcssAnimate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
const config = {
    darkMode: ['class'],
    content: [
        './pages/**/*.{js,jsx,ts,tsx}',
        './components/**/*.{js,jsx,ts,tsx}',
        './app/**/*.{js,jsx,tsx}',
        './src/**/*.{js,jsx,ts,tsx}',
        './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
    ],
    container: {
        center: true,
        padding: '2rem',
        screens: {
            '2xl': '1400px',
        },
    },
    extend: {
        borderRadius: {
            lg: 'var(--radius)',
            md: 'calc(var(--radius) - 2px)',
            sm: 'calc(var(--radius) - 4px)',
        },
        keyframes: {
            'accordion-down': {
                from: {height: '0'},
                to: {height: 'var(--radix-accordion-content-height)'},
            },
            'accordion-up': {
                from: {height: 'var(--radix-accordion-content-height)'},
                to: {height: '0'},
            },
        },
        animation: {
            'accordion-down': 'accordion-down 0.2s ease-out',
            'accordion-up': 'accordion-up 0.2s ease-out',
        },
    },
    plugins: [tailwindcssAnimate,
        nextui(
            {
                prefix: 'next-ui',
                addCommonColors: false,
                defaultTheme: 'light',
                defaultExtendTheme: 'light',

                themes: {
                    light: {
                        colors: {
                            primary: 'hsl(28, 100%, 50%)',
                            secondary: 'hsl(210, 100%, 30%)',
                            destructive: 'hsl(0, 0%, 98%)',
                            muted: 'hsl(240, 4.8%, 95.9%)',
                            accent: 'hsl(120, 50%, 50%)',
                            popover: 'hsl(0, 0%, 100%)',
                            card: 'hsl(0, 0%, 100%)',
                        },
                        text: {
                            primary: 'hsl(0, 0%, 98%)',
                            secondary: 'hsl(0, 0%, 98%)',
                            destructive: 'hsl(0, 0%, 98%)',
                            muted: 'hsl(240, 3.8%, 46.1%)',
                            accent: 'hsl(240, 5.9%, 10%)',
                            popover: 'hsl(240, 10%, 3.9%)',
                            card: 'hsl(240, 10%, 3.9%)',
                        },
                        background: {
                            primary: 'hsl(28, 100%, 50%)',
                            secondary: 'hsl(210, 100%, 30%)',
                            destructive: 'hsl(0, 0%, 98%)',
                            muted: 'hsl(240, 4.8%, 95.9%)',
                            accent: 'hsl(120, 50%, 50%)',
                            popover: 'hsl(0, 0%, 100%)',
                            card: 'hsl(0, 0%, 100%)',
                        },
                        border: {
                            primary: 'hsl(240, 5.9%, 90%)',
                            secondary: 'hsl(240, 5.9%, 90%)',
                            destructive: 'hsl(240, 5.9%, 90%)',
                            muted: 'hsl(240, 5.9%, 90%)',
                            accent: 'hsl(240, 5.9%, 90%)',
                            popover: 'hsl(240, 5.9%, 90%)',
                            card: 'hsl(240, 5.9%, 90%)',
                        },
                        radius: {
                            lg: '0.5rem',
                            md: 'calc(0.5rem - 2px)',
                            sm: 'calc(0.5rem - 4px)',
                        },
                        shadow: {
                            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                            xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
                            '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
                            inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
                        },
                        gradient: {
                            primary: 'linear-gradient(90deg, hsl(28, 100%, 50%) 0%, hsl(210, 100%, 30%) 100%)',
                            secondary: 'linear-gradient(90deg, hsl(210, 100%, 30%) 0%, hsl(28, 100%, 50%) 100%)',
                            destructive: 'linear-gradient(90deg, hsl(0, 0%, 98%) 0%, hsl(210, 100%, 30%) 100%)',
                            muted: 'linear-gradient(90deg, hsl(240, 4.8%, 95.9%) 0%, hsl(210, 100%, 30%) 100%)',
                            accent: 'linear-gradient(90deg, hsl(120, 50%, 50%) 0%, hsl(210, 100%, 30%) 100%)',
                            popover: 'linear-gradient(90deg, hsl(0, 0%, 100%) 0%, hsl(210, 100%, 30%) 100%)',
                            card: 'linear-gradient(90deg, hsl(0, 0%, 100%) 0%, hsl(210, 100%, 30%) 100%)',
                        },
                        transition: {
                            default: 'all 0.3s ease',
                            none: 'none',
                        },
                        typography: {
                            fontFamily: 'var(--font-family)',
                            fontSize: 'var(--font-size)',
                            fontWeight: 'var(--font-weight)',
                            lineHeight: 'var(--line-height)',
                            letterSpacing: 'var(--letter-spacing)',
                        },
                        zIndex: {
                            0: 0,
                            10: 10,
                            20: 20,
                            30: 30,
                            40: 40,
                            50: 50,
                            100: 100,
                            200: 200,
                            300: 300,
                            400: 400,
                            500: 500,
                            600: 600,
                            700: 700,
                            800: 800,
                            900: 900,
                            1000: 1000,
                            auto: 'auto',
                        },
                        spacing: {
                            0: '0',
                            1: '0.25rem',
                            2: '0.5rem',
                            3: '0.75rem',
                            4: '1rem',
                            5: '1.25rem',
                            6: '1.5rem',
                            7: '1.75rem',
                            8: '2rem',
                            9: '2.25rem',
                            10: '2.5rem',
                            11: '2.75rem',
                            12: '3rem',
                            14: '3.5rem',
                            16: '4rem',
                            20: '5rem',
                            24: '6rem',
                            28: '7rem',
                            32: '8rem',
                            36: '9rem',
                            40: '10rem',
                            44: '11rem',
                            48: '12rem',
                            52: '13rem',
                            56: '14rem',
                            60: '15rem',
                            64: '16rem',
                            72: '18rem',
                            80: '20rem',
                            96: '24rem',
                        },
                        screens: {
                            sm: '640px',
                            md: '768px',
                            lg: '1024px',
                            xl: '1280px',
                            '2xl': '1536px',
                        },
                    },
                    dark: {
                        colors: {
                            primary: 'hsl(210, 100%, 30%)',
                            secondary: 'hsl(28, 100%, 50%)',
                            destructive: 'hsl(0, 100%, 50%)',
                            muted: 'hsl(240, 3.7%, 15.9%)',
                            accent: 'hsl(120, 50%, 50%)',
                            popover: 'hsl(240, 10%, 3.9%)',
                            card: 'hsl(240, 10%, 3.9%)',
                        },
                        text: {
                            primary: 'hsl(0, 0%, 98%)',
                            secondary: 'hsl(0, 0%, 98%)',
                            destructive: 'hsl(0, 0%, 98%)',
                            muted: 'hsl(240, 5%, 64.9%)',
                            accent: 'hsl(0, 0%, 98%)',
                            popover: 'hsl(0, 0%, 98%)',
                            card: 'hsl(0, 0%, 98%)',
                        },
                        background: {
                            primary: 'hsl(210, 100%, 30%)',
                            secondary: 'hsl(28, 100%, 50%)',
                            destructive: 'hsl(0, 100%, 50%)',
                            muted: 'hsl(240, 3.7%, 15.9%)',
                            accent: 'hsl(120, 50%, 50%)',
                            popover: 'hsl(240, 10%, 3.9%)',
                            card: 'hsl(240, 10%, 3.9%)',
                        },
                        border: {
                            primary: 'hsl(240, 3.7%, 15.9%)',
                            secondary: 'hsl(240, 3.7%, 15.9%)',
                            destructive: 'hsl(240, 3.7%, 15.9%)',
                            muted: 'hsl(240, 3.7%, 15.9%)',
                            accent: 'hsl(240, 3.7%, 15.9%)',
                            popover: 'hsl(240, 3.7%, 15.9%)',
                            card: 'hsl(240, 3.7%, 15.9%)',
                        },
                        radius: {
                            lg: '0.5rem',
                            md: 'calc(0.5rem - 2px)',
                            sm: 'calc(0.5rem - 4px)',
                        },
                        shadow: {
                            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                            xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
                        },
                        gradient: {
                            primary: 'linear-gradient(90deg, hsl(28, 100%, 50%) 0%, hsl(210, 100%, 30%) 100%)',
                            secondary: 'linear-gradient(90deg, hsl(210, 100%, 30%) 0%, hsl(28, 100%, 50%) 100%)',
                            destructive: 'linear-gradient(90deg, hsl(0, 100%, 50%) 0%, hsl(210, 100%, 30%) 100%)',
                            muted: 'linear-gradient(90deg, hsl(240, 3.7%, 15.9%) 0%, hsl(210, 100%, 30%) 100%)',
                            accent: 'linear-gradient(90deg, hsl(120, 50%, 50%) 0%, hsl(210, 100%, 30%) 100%)',
                            popover: 'linear-gradient(90deg, hsl(240, 10%, 3.9%) 0%, hsl(210, 100%, 30%) 100%)',
                            card: 'linear-gradient(90deg, hsl(240, 10%, 3.9%) 0%, hsl(210, 100%, 30%) 100%)',
                        },
                        transition: {
                            default: 'all 0.3s ease',
                            none: 'none',
                        },
                        typography: {
                            fontFamily: 'var(--font-family)',
                            fontSize: 'var(--font-size)',
                            fontWeight: 'var(--font-weight)',
                            lineHeight: 'var(--line-height)',
                            letterSpacing: 'var(--letter-spacing)',
                        },
                        zIndex: {
                            0: 0,
                            10: 10,
                            20: 20,
                            30: 30,
                            40: 40,
                            50: 50,
                            100: 100,
                            200: 200,
                            300: 300,
                            400: 400,
                            500: 500,
                            600: 600,
                            700: 700,
                            800: 800,
                            900: 900,
                            1000: 1000,
                            auto: 'auto',
                        },
                        spacing: {
                            0: '0',
                            1: '0.25rem',
                            2: '0.5rem',
                            3: '0.75rem',
                            4: '1rem',
                            5: '1.25rem',
                            6: '1.5rem',
                            7: '1.75rem',
                            8: '2rem',
                            9: '2.25rem',
                            10: '2.5rem',
                            11: '2.75rem',
                            12: '3rem',
                            14: '3.5rem',
                            16: '4rem',
                            20: '5rem',
                            24: '6rem',
                            28: '7rem',
                            32: '8rem',
                            36: '9rem',
                            40: '10rem',
                            44: '11rem',
                            48: '12rem',
                            52: '13rem',
                            56: '14rem',
                            60: '15rem',
                            64: '16rem',
                            72: '18rem',
                            80: '20rem',
                            96: '24rem',
                        },
                        screens: {
                            sm: '640px',
                            md: '768px',
                            lg: '1024px',
                            xl: '1280px',
                            '2xl': '1536px',
                        },
                    },
                },
            },
        )],
};

export default config;
