services:
  sthenosfit-nginx:
    container_name: "${COMPOSE_PROJECT_NAME:-SthenosFit}_sthenosfit_nginx"
    restart: "${DOCKER_RESTART_POLICY:-always}"
    build:
      context: docker/sthenosfit_nginx
    environment:
      VIRTUAL_HOST: "${STHENOS_FIT_HOSTNAMES:?}"
      LETSENCRYPT_HOST: "${STHENOS_FIT_HOSTNAMES:?}"
    expose:
      - "80"
    volumes:
      - api_static:/srv/api/
    depends_on:
      - frontend
      - api
    networks:
      - default
      - net_sthenosfit_frontend
      - net_sthenosfit_backend
      - net_sthenosfit_database
      
  frontend:
    hostname: frontend
    container_name: "${COMPOSE_PROJECT_NAME:-SthenosFit}_frontend"
    restart: "${DOCKER_RESTART_POLICY:-always}"
    environment:
      TERM: xterm-256color
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET:?}"
      NEXTAUTH_URL: "${NEXTAUTH_URL:?}"
      NEXTAUTH_API_BASE_URL: http://sthenosfit-nginx/
      NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL:?}"
      GOOGLE_ID: "${NEXTAUTH_GOOGLE_ID:?}"
      GOOGLE_SECRET: "${NEXTAUTH_GOOGLE_SECRET:?}"
      FACEBOOK_ID: "${NEXTAUTH_FACEBOOK_ID:?}"
      FACEBOOK_SECRET: "${NEXTAUTH_FACEBOOK_SECRET:?}"
      TOKEN_WGER: "800b7aa0791502236edb8e097fc603c1b0b2be99"
      WGER_API_URL: "https://wger.de/api/v2/"
    expose:
      - "3000"
    depends_on:
      - api
    networks:
      - net_sthenosfit_frontend
  api:
    hostname: api

    container_name: "${COMPOSE_PROJECT_NAME:-sthenosfit-ng}_api"
    restart: "${DOCKER_RESTART_POLICY:-always}"
    environment:
      TERM: xterm-256color
      DJANGO_SETTINGS_MODULE: "${STHENOS_FIT_DJANGO_SETTINGS_MODULE:-SthenosFit.settings}"
      DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL:-INFO}"
      DJANGO_ALLOWED_HOSTS: "${STHENOS_FIT_HOSTNAMES:-localhost},sthenosfit-nginx"
      DJANGO_SECRET_KEY: "${STHENOS_FIT_DJANGO_SECRET_KEY:?}"
      DJANGO_DATABASE_NAME: "${STHENOS_FIT_POSTGRES_DB:-sthenosfit}"
      DJANGO_DATABASE_USER: "${STHENOS_FIT_POSTGRES_USER:-sthenosfit}"
      DJANGO_DATABASE_PASSWORD: "${STHENOS_FIT_POSTGRES_PASSWORD:?}"
      DJANGO_DATABASE_HOST: SthenosFit-postgres
      DJANGO_DATABASE_PORT: "5432"
      SIMPLEJWT_SECRET_KEY: "${SIMPLEJWT_SECRET_KEY:?}"
      PGHOST: SthenosFit-postgres
      PGUSER: "${STHENOS_FIT_POSTGRES_USER:-SthenosFit}"
    expose:
      - "8000"
    volumes:
      - api_static:/srv/django
    depends_on:
      - sthenosfit-postgres
    networks:
      - net_sthenosfit_frontend
      - net_sthenosfit_backend
      - net_sthenosfit_database


  sthenosfit-postgres:
    image: "postgres:${STHENOS_FIT_POSTGRES_VERSION:?}"
    container_name: "${COMPOSE_PROJECT_NAME:-sthenosfit-ng}_sthenosfit_postgres"
    restart: "${DOCKER_RESTART_POLICY:-always}"
    environment:
      POSTGRES_DB: "${STHENOS_FIT_POSTGRES_DB:-sthenosfit}"
      POSTGRES_USER: "${STHENOS_FIT_POSTGRES_USER:-sthenosfit}"
      POSTGRES_PASSWORD: "${STHENOS_FIT_POSTGRES_PASSWORD:?}"
    expose:
      - "5432"
    volumes:
      - sthenosfit_postgres:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - net_sthenosfit_database  
volumes:
  api_static:
  sthenosfit_postgres:

networks:
  net_sthenosfit_backend:
  net_sthenosfit_database:
  net_sthenosfit_frontend:
