name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push frontend image
      run: |
        docker build -t ghcr.io/tu-usuario/frontend:latest -f Dockerfile.frontend .
        docker push ghcr.io/tu-usuario/frontend:latest

    - name: Build and push api image
      run: |
        docker build -t ghcr.io/tu-usuario/api:latest -f Dockerfile.api .
        docker push ghcr.io/tu-usuario/api:latest

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@your-ec2-instance:/home/ec2-user/
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance << 'EOF'
          docker-compose pull
          docker-compose up -d
          docker-compose exec -T api make migrate static
          docker-compose restart
        EOF
